// <auto-generated />
using System;
using CDISC_StopSpildLokaltBackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDISC_StopSpildLokaltBackEnd.Migrations
{
    [DbContext(typeof(OrganizationalDBContext))]
    [Migration("20191005135138_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Identification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTs");

                    b.HasKey("Id");

                    b.ToTable("Identification");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Organization", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTs");

                    b.HasKey("Name");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int?>("ContactPersonId");

                    b.Property<DateTime>("CreatedTs");

                    b.Property<string>("Description");

                    b.Property<string>("FacebookUrl");

                    b.Property<string>("OrganizationName");

                    b.Property<string>("Postcode");

                    b.Property<string>("TeamName");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("OrganizationName");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken");

                    b.Property<DateTime>("CreatedTs");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("IdentificationId");

                    b.Property<string>("LastName");

                    b.Property<string>("OrganizationName");

                    b.Property<string>("Phonenumber");

                    b.Property<string>("Postcode");

                    b.Property<int?>("TeamId");

                    b.Property<int>("VolunteerType");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId")
                        .IsUnique();

                    b.HasIndex("OrganizationName");

                    b.HasIndex("TeamId");

                    b.ToTable("Volunteer");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Team", b =>
                {
                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Volunteer", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId");

                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationName");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Volunteer", b =>
                {
                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Identification", "Identification")
                        .WithOne("Volunteer")
                        .HasForeignKey("CDISC_StopSpildLokaltBackEnd.Volunteer", "IdentificationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Organization", "Organization")
                        .WithMany("Volunteers")
                        .HasForeignKey("OrganizationName");

                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Team")
                        .WithMany("Volunteers")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
