// <auto-generated />
using System;
using CDISC_StopSpildLokaltBackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CDISC_StopSpildLokaltBackEnd.Migrations
{
    [DbContext(typeof(OrganizationalDBContext))]
    [Migration("20191001123143_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Identification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTs");

                    b.HasKey("Id");

                    b.ToTable("Identification");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("ContactPersonId");

                    b.Property<DateTime>("CreatedTs");

                    b.Property<string>("Description");

                    b.Property<string>("FacebookUrl");

                    b.Property<int>("OrganizationId");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("TeamName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken");

                    b.Property<DateTime>("CreatedTs");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("IdentificationId");

                    b.Property<string>("LastName");

                    b.Property<int?>("OrganizationId");

                    b.Property<string>("Phonenumber");

                    b.Property<string>("Postcode");

                    b.Property<int?>("TeamId");

                    b.Property<int>("VolunteerType");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationId")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.ToTable("Volunteer");
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Team", b =>
                {
                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Volunteer", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CDISC_StopSpildLokaltBackEnd.Volunteer", b =>
                {
                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Identification", "Identification")
                        .WithOne("Volunteer")
                        .HasForeignKey("CDISC_StopSpildLokaltBackEnd.Volunteer", "IdentificationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Organization", "Organization")
                        .WithMany("Volunteers")
                        .HasForeignKey("OrganizationId");

                    b.HasOne("CDISC_StopSpildLokaltBackEnd.Team")
                        .WithMany("Volunteers")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
